import type { Metadata } from "next";
import { PT_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AOSProvider from "@/provider/AOSProvider";


const ptSans = PT_Sans({ subsets: ["latin"], weight:["400","700"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn('min-h-screen font-sans antialiased',ptSans.className) }
      >
        <AOSProvider>
          <nav >
          <Navbar/>
        </nav>
        {children}
        <footer>
          <Footer/>
        </footer>
        </AOSProvider>
      </body>
    </html>
  );
}
